### ISSUE TITLE
Allocations State does not load correctly

### ISSUE THREAD

**Issue by topocount** [AutarkLabs/planning-suite#308]
Upon clearing the cache, only the most recently created allocations card is loading into the front end.

**Comment by Quazia** [comment]
I think this was resolved but I'm not positive... If it wasn't I think it's related to #313

**Comment by topocount** [comment]
@quazia do you mind posting the commit ref?

**Comment by stellarmagnet** [comment]
This issue still exists when testing in rinkeby-demo.

Steps to reproduce:

* Create two Accounts
* Clear cache

You will see the first account disappears

**Comment by topocount** [comment]
I'm pretty confident @ottodevs fixed this when he got the store working

**Comment by Quazia** [comment]
Confirmed this is resolved. Closing and removing weight/assignment.
